### ISSUE TITLE
Dialog: Requires Unsafe Mode

### ISSUE THREAD

**Issue by ArkSource** [devnoname120/vhbb#16]
installation notification if target homebrew requires unsafe mode to run.

**Comment by 0xakrem** [comment]
thanks !

**Comment by devnoname120** [comment]
I'm not fond of this change. I think that adding a dialog is fear-inducing and anyway useless since users aren't able to verify by themselves if a homebrew is malicious or not. This encourages them to blindly ignore security dialogs, which is a bad habit.

If some users are paranoid and wish not to install any "unsafe" homebrew, then I'm sorry they will have to manually download and install homebrews with Vitashell.

Now, once VHBB becomes opensource, if someone decides to implement it in a pull request and **disable the warnings by default**, then I'm not against merging it.
