### ISSUE TITLE
Bermuda Syndrome (porting hosted on homebrew browser)

### ISSUE THREAD

**Issue by Spartk** [devnoname120/vhbb#34]
This game, downloaded from homebrew browser, installs fine but it doesn't start.

**Comment by devnoname120** [comment]
Does it work if you install it manually using Vitashell from here?
http://vitadb.rinnegatamante.it/#/info/115

**Comment by rsn8887** [comment]
The VitaDB data files only contain the music, but not the program files. I think this is intentional. 

To make the game work, you have to download the actual game data file and unzip it and copy the files over to ux0:data/bermuda

A link to the data files is found here in the release notes: https://github.com/usineur/bermuda/releases

**Comment by devnoname120** [comment]
@usineur It might be helpful to add a message on the start of the homebrew to let users know that they need to copy the data files.

Anyway, this isn't related to VHBB.

**Comment by usineur** [comment]
I already thought about adding this kind of control. But every steps are given in my instructions to avoid this situation.

I can figure this is not a VHBB issue - and I agree with that -, but is the description page enough clear about this point now (website + app) ?

**Comment by devnoname120** [comment]
Not really, but I don't think most people don't read the description.
