### ISSUE TITLE
Doing anything kills the app instantly.

### ISSUE THREAD

**Issue by indianaliam1** [devnoname120/vhbb#87]
[VHBB_2020-09-02_19-16-11.log](https://github.com/devnoname120/vhbb/files/5164073/VHBB_2020-09-02_19-16-11.log)

This. Doing anything kills my Vita. It's a Phat Vita.

**Comment by Masamune3210** [comment]
good way to ask for support, totally

**Comment by indianaliam1** [comment]
I know, thanks!

**Comment by Masamune3210** [comment]
What's the point of the attitude? Why even make a issue

**Comment by indianaliam1** [comment]
Because I can't use the app? Why make a comment?

**Comment by theAkito** [comment]
@indianaliam1 

Forget this dude. I am sure, with this attitude, you will find plenty of people craving to help you. Everyone will fight each other to come to your 1st priority issue, to get it solved for you. Everyone will be so sorry, because of your precious and so valuable time being stolen by this error. Wait for the army of people leaving work, leaving school, leaving hospital, because **you** need help!

**Comment by robsdedude** [comment]
Try again with one of those three options:
 - Pay someone to fix it. Then you might have the right to demand anything.
 - Learn to code yourself and fix it.
 - Ask kindly, be polite, and hope for someone willing to invest more of their leisure time for free to fix the problem.
